<template>
    <div ref="wrapper">
      <slot></slot>
    </div>
</template>
<script>
  import BScroll from "better-scroll";
  export default {
    props:{
      data:{
        type:Array,
        default:null
      },
      listenScroll:{
        type:Boolean,
        default:false
      },
      probeType:{
        type:Number,
        default:1
      }
    },
    mounted(){
      setTimeout(()=>{
        this._initScroll();
      },30)
    },
    methods:{
      _initScroll(){
        this.scroll = new BScroll(this.$refs.wrapper,{
          probeType:this.probeType,
          click:true
        });
        if(this.listenScroll){
          this.scroll.on('scroll',(pos)=>{
            this.$emit('scroll',pos)
          })
        }
      },
      refresh(){
        this.scroll&&this.scroll.refresh();
      },
      scrollToElement(){
        this.scroll&&this.scroll.scrollToElement.apply(this.scroll,arguments)
      },
      scrollTo(){
        this.scroll&&this.scroll.scrollTo.apply(this.scroll,arguments)
      }
    },
    watch:{
      data(){
        setTimeout(()=>{
            this.refresh();
        },30)
      }
    }
  }
</script>
<style>

</style>
